= 종속성

새티스팩토리 모딩을 시작하려면
먼저 여러 개의 소프트웨어가 설치되어 있어야 합니다.

걱정하지 마세요. 이러한 종속성을 다운로드하고 설치해야 하는
단계를 모두 설명해 두었습니다.

이것은 매우 긴 과정이 될 수 있습니다.
그래서 다른 일을 해야 한다면
다시 시작하기 쉽도록 중단한 위치를 적어 두세요.

모딩 환경은 많은 공간을 차지할 수 있습니다.
모든 것이 설치되고 구축되면 30GB 정도를 차지할 수 있습니다.
모든 파일을 저장할 위치를 결정할 때 이 점을 명심하세요.
남은 공간이 거의 없는 드라이브에 보관하지 마세요.

[TIP]
====
다른 형식의 가이드를 선호하는 경우 https://www.youtube.com/watch?v=-HVw6-3Awqs[이러한]
영상 튜토리얼 확인해보세요.
**SML 3.0.0부터 이 영상 튜토리얼은 사용할 수 없습니다.
그러나 일부 개념은 같을 겁니다.**
영상 튜토리얼에서 멈춘 경우 여기로 돌아와서 대신 이 가이드를 따르세요.
올바르게 수행하고 있는지 확인하려면 여기에 있는 단계를 자세히 읽어보세요.
====

== 계속하기 전에

xref:Development/BeginnersGuide/index.adoc[시작하기 머리글 페이지]에서
시작 정보를 읽었는지 확인하세요.
이 문서를 사용하는 방법에 대한 중요한 정보를 알 수 있습니다.

== 새티스팩토리

이것은 매우 간단하며 이미 수행했으리라 믿습니다.
에픽 게임즈 런처 또는 스팀에서 새티스팩토리를 구매, 다운로드 및 설치하기만 하면 됩니다.
모든 파일이 올바르게 설정되도록 게임을 한 번 이상 실행해주세요.

== 비주얼 스튜디오

https://visualstudio.microsoft.com/downloads/[마이크로소프트 비주얼 스튜디오 다운로드 페이지]를 방문하여 원하는 버전을 다운로드하세요.
무료이고 현대적인 Visual Studio 2022 커뮤니티를 추천합니다.
이전 버전에 액세스하려면 가입해야 할 수 있지만 무료입니다.

설치 프로그램을 실행하고 도중에 표시되는 메시지에 동의합니다.
"워크로드" 페이지에서 "데스크탑 및 모바일 > {cpp}를 사용한 데스크탑 개발" 및 "게임 > {cpp}를 사용한 게임 개발"을 선택합니다.
찾으려면 조금 내려봐야 할 수도 있습니다.

비주얼 스튜디오가 이미 설치되어 있는 경우 설치 관리자를 다시 실행하고 '수정'을 선택하여 이 두 워크로드를 선택하여 설치에 추가할 수 있습니다.

나머지 과정을 계속 진행하여 비주얼 스튜디오를 설치합니다.
비주얼 스튜디오를 다운로드하고 설치하는 데 시간이 걸릴 수 있으므로 기다리는 동안 도마멍멍이를 쓰다듬고 있거나 아래의 다른 설치 단계 중 일부를 작업하는 것이 좋습니다.

[WARNING]
====
4.6 버전 이상 (코어/v5 제외)의 .NET 프레임워크 SDK 또한 필요합니다.
.NET 프레임워크 SDK가 설치되어 있는지 확실하지 않다면
VS 설치 프로그램이 설치 옵션을 제공할 겁니다. 체크하는 것이 좋습니다.
====

[TIP]
====
{cpp} 모더들 사이에서 비주얼 스튜디오를 대체할 인기 있는 것은
https://www.jetbrains.com/lp/rider-unreal/[Rider for Unreal Engine]입니다.
사용을 고려한다면 필요한 VS-{cpp} 패키지가 설치되어 있는지 확인하세요.
====

== 언리얼 엔진 4 (커스텀 엔진)

새티스팩토리는 언리얼 엔진의 수정 버전을 사용하기 때문에,
우리 모더는 모드를 개발하기 위해 동일한 버전을 사용해야 합니다.

다른 목적으로 이미 언리얼 엔진을 설치했다면,
해당 설치는 새티스팩토리 모딩에 대해 **작동하지 않습니다.**
아래 단계를 쭉 따라가세요.

=== 깃허브를 에픽 게임즈 개발자 계정에 연결

이 과정에서는 깃허브 계정이 필요합니다.
가지고 있지 않은 경우
https://github.com/signup[여기에서] 하나 만드세요.

깃허브 계정을 가지고 있다면,
에픽 게임즈에 등록하고 에픽 게임즈 깃허브 조직에 가입해야 이 특별한 버전을 다운로드할 수 있습니다.
https://www.unrealengine.com/en-US/ue4-on-github[여기]에서 연결하는 방법을 확인하세요.

"Sorry, the service is temporarily unavailable. Please try back later."
문구가 표시된다면 활성화 된 광고 차단기나 콘텐츠 필터를 끄고 페이지를 완전히 새로고침해 보세요 (Ctrl+Shift+R).

아마도 이메일을 확인하고 거기에서 확인해야 할 뿐만 아니라
앞의 링크를 들어갈 때 연결된 깃허브 계정에 로그인되어 있는지 확인해야 할 것입니다.

=== 커스텀 엔진 파일 다운로드

이 작업을 완료했다면
https://github.com/SatisfactoryModdingUE/UnrealEngine/releases[새티스팩토리 모딩 언리얼 엔진 프로젝트]로 이동해
최신 릴리즈에서 다음 파일들을 다운로드하세요.

- `UnrealEngine-CSS-Editor-Win64-1.bin`
- `UnrealEngine-CSS-Editor-Win64-2.bin`
- `UnrealEngine-CSS-Editor-Win64.exe`

[WARNING]
====
"404 This is not the web page you are looking for" 오류가 표시되면
계정 연결이 완료되지 않은 것입니다.
페이지가 _죽은게_ 아니라면, 이 오류는 누군가 개인 저장소에 접근하려고 할 때 보안 차원으로 깃허브가 표시하는 겁니다.

에픽과 깃허브에서 보낸 이메일을 확인하고 위의 단계를 따랐는지 확인하세요.
https://github.com/settings/organizations[깃허브 계정 조직 페이지]에서
"EpicGames"를 확인하여 깃허브 조직에 올바르게 가입했는지 확인할 수 있습니다.
깃허브 계정이 에픽 게임즈 페이지에 이미 연결된 것으로 표시되어 있으면 연결을 해제했다가 다시 연결하여 깃허브 조직 초대를 다시 보낼 수 있습니다.
====

=== 커스텀 엔진 설치

3개의 파일 모두 다운로드가 완료되면
.exe를 실행하고 프롬프트에 따라 커스텀 언리얼 엔진 버전과 해당 에디터를 설치하세요.

[WARNING]
====
설치 프로그램에서 다음 매체 파일이 있는 폴더를 선택하라는 메시지가 표시되면 다운로드한 두 개의 `.bin` 파일이 포함된 폴더를 선택하세요.

또한 위에서 설명한 대로 다운로드한 파일의 이름을 정확히 지정해야 합니다. 그렇지 않으면 설치 프로그램이 두 개의 `.bin` 파일을 찾지 못할 수 있습니다.
====

이 설치 과정과 나중에 언리얼을 처음으로 여는 데 시간이 좀 걸릴 수 있습니다.
아직 언리얼을 여는 것에 대해 걱정하지 마세요.
아직 제대로 설정하지 않은 항목을 컴파일하도록 요청할 것입니다.

// Visual Studio extension no longer needed, but may be needed when dedicated server support comes out for easily building multiple targets
// === Install the Visual Studio Extension

== Wwise

Wwise는 Coffee Stain에서 사용하는 사운드 엔진이며,
모드를 개발하려면 사운드를 수정할 계획이 없더라도
Wwise를 설치하고 모드 프로젝트와 통합해야 합니다.

https://www.audiokinetic.com/products/wwise/[Wwise]를 방문하여 오른쪽 상단 모서리에 있는 `+Get Wwise+` -> `+Download Wwise+` 버튼을 클릭하세요.
다운로드 버튼을 클릭하면 로그인하라는 메시지가 표시됩니다.
아직 계정이 없다면 계정을 생성하거나 로그인하여 런처를 다운로드하세요.
Wwise 다운로드를 마친 후 설치 프로그램을 엽니다.

상단 표시줄에서 `WWISE` 를 선택합니다.
`Latest` 드롭다운을 클릭하고 `All` 로 변경합니다.
다음 드롭다운에서 `2021.1` 을 선택합니다.
최종 드롭다운에서 버전 `2021.1.0.7575` 를 선택합니다.
`Install` 을 클릭합니다.

[TIP]
====
정확한 Wwise 버전이 표시되지 않으면 `2021.1` 로 시작하는 다른 최신 버전을 시도해 보세요.
====

설치할 항목에 대한 옵션이 표시되면 다음을 선택합니다.

* Packages
** Authoring
** SDK (C++)
* Deployment Platforms
** Apple
*** macOS
** Microsoft 
*** Windows
**** Visual Studio 2017
**** Visual Studio 2019

`다음` 을 클릭합니다.
플러그인을 추가할 필요가 없으므로 `Install` 을 눌러 왼쪽 하단에서 건너뛰고 설치 과정을 시작하세요.
도중에 나타나는 이용 약관 메시지에 동의합니다.

[TIP]
====
Wwise 통합 중에 checksum 오류가 발생하면 다른 Wwise 버전을 설치하면 문제가 해결됩니다.
====

== 스타터 프로젝트

SML 개발 팀은 새티스팩토리 모드 로더, 기본 게임 콘텐츠용 플레이스홀더 에셋, 몇 가지 유용한 개발자 플러그인이 미리 설치된 언리얼 프로젝트를 준비했습니다.

이 `스타터 프로젝트` 내에서 파일을 별도로 유지하면서 원하는 만큼 많은 모드를 개발할 수 있습니다. 이에 대해서는 나중에 문서에서 다룰 것입니다.

버전 관리 소프트웨어 (예: Git)에 익숙하다면 https://github.com/satisfactorymodding/SatisfactoryModLoader/[저장소 복제]를 권장합니다. 이렇게 하면 나중에 게임이 업데이트될 때 파일 업데이트 과정이 대폭 간소화됩니다.
`master` 일 가능성이 높지만 디스코드에서 복제할 분기를 찾으세요.

버전 관리에 익숙하지 않다면
https://www.gitkraken.com/learn/git/tutorials[지금이 배우기에 좋은 때입니다]!
VCS(Version Control Software)를 사용하는 것은 개발자에게 훌륭한 기술이며 향후 프로젝트를 업데이트하는 데 큰 도움이 될 뿐만 아니라
깃허브 같은 호스팅 웹사이트에 모드 소스를 업로드하는 경우 모드 소스를 잃지 않도록 보호합니다.

그러나 모딩을 시작하려는 경우 새티스팩토리 모딩 깃허브에서 시작 프로젝트의 zip을 다운로드하거나
https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/heads/master.zip[이 링크]를 통해 직접 다운로드할 수 있습니다.

아직 다운로드한 파일로 아무 작업도 하지 마세요. 다음 페이지인 프로젝트 설정에서 다룰 것입니다.

== 새티스팩토리 모드 관리자

xref:index.adoc#_새티스팩토리_모드_관리자_일명_smm[새티스팩토리 모드 관리자]는 올바른 버전의 SML을 자동으로 설치하고 모드 파일을 관리하는 데 도움이 되는 편리한 개발자 모드를 제공합니다.
활성화하려면 선택한 프로필을 `development` 로 변경하세요.
새티스팩토리 모드 관리자를 사용하는 경우 아래 단계를 건너뛰고 튜토리얼의 다음 페이지로 이동할 수 있습니다.

모드 관리자를 사용하지 않는 경우 다음을 따라야 합니다.
관련 파일을 설정하려면 xref:ManualInstallDirections.adoc[수동 설치 지침]을 참조하세요.

또는 모딩 환경이 설정되면 알파킷을 사용하여 SML을 자동으로 빌드하고 설치할 수 있습니다.
이 과정은 다음 페이지에서 다룹니다.

== 다음 단계

이제 모든 종속성이 설치되었으므로 xref:Development/BeginnersGuide/project_setup.adoc[프로젝트 설정]으로 이동할 수 있습니다.
