= 새티스팩토리 모딩 문서

== 기본

새티스팩토리 모딩 문서 사이트에 오신 것을 환영합니다!

여기에서 https://www.satisfactorygame.com/[새티스팩토리], https://www.coffeestainstudios.com/games/[커피 스테인 스튜디오](CSS)의 공장 건설 시뮬레이션에 관한 많은 정보를 찾을 수 있습니다. 새티스팩토리를 위한 모딩은 게임이 출시된 지 오래됐음에도 생각보다 더 확고합니다. 이미 https://ficsit.app/[수많은 모드]가 출시되어 있으며 직접 새로운 모드를 개발할 수 있는 여러 가지 방법이 있습니다. 

이 페이지에서는 모드 사용자와 개발자 모두를 위한 몇 가지 겉보기 수준 정보를 제공합니다.

[TIP]
====
이 훌륭한 커뮤니티에 참여하고 싶다면 저희의
https://discord.gg/xkVJ73E[디스코드 서버]에 들어오세요.
====

== 일반 사용자를 위해

모드를 사용해 보고 싶으시다면, 이 섹션이 적합하겠군요.

=== 새티스팩토리 모드 저장소 [.title-ref]#(일명. SMR 일명. ficsit.app 일명. FICSIT 증강 데이터베이스)#

새티스팩토리 모드 저장소(SMR)는 새티스팩토리 전용으로 만들어진 가장 광범위한 모드 모음입니다.
나만의 모드를 업로드하거나 다른 사용자를 위한 가이드를 작성하는 것은 쉽습니다.
업로드된 콘텐츠는 다운로드가 승인되기 전에 멀웨어 등에 대한 테스트를 거칩니다.
자세한 내용은 https://ficsit.app/[ficsit.app]을 방문하세요.

=== 새티스팩토리 모드 관리자 [.title-ref]#(일명. SMM)#

새티스팩토리 모드 관리자를 사용하면 최종 사용자가 모드, 모드의 종속성 및 모드 로더를 쉽게 설치할 수 있습니다.
https://ficsit.app/[SMR]에 연결되어 모든 모드를 빠르고 쉽게 설치할 수 있습니다.

https://github.com/satisfactorymodding/SatisfactoryModLauncher/releases[깃허브]에서 확인하세요!

`winget install SatisfactoryModding.SatisfactoryModManager` 를 통해 winget으로 설치할 수도 있습니다.

최종 사용자로 모드를 설치하려면 모드를 훨씬 쉽게 사용할 수 있는 새티스팩토리 모드 관리자를 사용하는 것이 좋습니다.
그러나 런처를 _정말로_ 사용하기 싫으면 xref:ManualInstallDirections.adoc[여기]에서
수동 설치 지침을 확인할 수 있습니다.

[TIP]
====
런처는 설치 과정을 간소화 해주기 때문에 모드를 사용하는 데 강력 추천합니다.
====

== 개발자를 위해

자신만의 모드를 만들어 보고 싶으시다면, 이 섹션이 적합할 것 같네요.

새티스팩토리 모드 관리자는 SML을 자동으로 설치하는 편리한 개발자 모드를 제공합니다. 활성화하려면 선택한 프로필을 `development` 로 변경하세요.

자신만의 모드를 작성하려는 경우 C++ 모드보다 pak 모드를 먼저 만드는 것으로 시작하는 것이 좋습니다. xref:Development/BeginnersGuide/index.adoc[시작 안내서]에서 자세히 알아보세요.

모델을 만들려고 한다면 먼저 모드를 업로드하는 방법을 배우는 것이 가장 좋습니다.
`초심자 가이드` 에서 `빌드하기` 단계를 완료한 후 xref:Development/Modeling/index.adoc[모델링 가이드]를 확인하세요.

=== "Raw" 또는 WIP 모드 설치

아직 패키징된 모드가 없다면 알파킷으로 만드세요.

압축한 모드(.zip 보관 모드)가 있는 경우 `<SF 경로>/FactoryGame/Mods/<모드 이름>` 에 압축을 풀기만 하면 됩니다. `.uplugin` 파일이 `<모드 이름>` 폴더 내에 _직접_ 포함되어 있는지 확인하세요.

=== 모드를 SMR에 업로드

모드(또는 최소한 첫 번째 버전)를 완료한 후 https://ficsit.app/[SMR]에 업로드할 수 있습니다. xref:UploadToSMR.adoc[여기]에서 자세한 방법을 알아보려면 전용 문서 페이지를 읽어보세요!

== 보관된 포럼

커뮤니티는 모딩 토론을 위한 Discourse 기반 양식 웹사이트를 가지고 있었지만 이후 사용량이 적어 보관되었습니다.
보관소는 https://forums.ficsit.app/[여기]에서 찾을 수 있습니다.

== 기여

이 한국어 문서는 비공식적으로 제작되었습니다. 2023년 4월 기준 공식 문서를 포크해 제작되었으며, 불완전한 부분이 있을 수 있습니다.
문서에서 수정해야 할 사항을 발견했다면 수정 후 풀 요청을 보내거나 디스코드 `versebrik#6788` 로 잘못된 부분을 지적하여 DM하여 주시기 바랍니다.

공식 문서에 대한 기여는 https://github.com/satisfactorymodding/Documentation#contributing[깃허브 저장소의 readme] 문서에서 찾을 수 있습니다.

== 모딩 기술

모딩이 내부적으로 작동하는 방식에 대해 자세히 알고 싶다면 이 섹션을 참조하세요.

=== 새티스팩토리 모드 로더 [.title-ref]#(일명. SML)#

새티스팩토리 모드 로더 (SML)는 모드를 더 쉽게 사용할 수 있도록 하는 프레임워크를 제공합니다.
게임에서 제공하는 시스템에 로드하고 서로 상호 작용합니다.
또한 모드 개발을 지원하는 많은 도우미 기능을 제공합니다.
CSS가 새티스팩토리를 구성한 방식으로 인해
SML이 작동하지 않아도 되는 모드를 만들 수 있습니다.
그러나 이것은 실제로 거의 수행되지 않습니다.

=== 알파킷

알파킷은 Mircea와 다른 기여자들이 만든 언리얼 엔진 플러그인으로 배포 및 배포를 위해 모드를 쉽게 쿠킹하고 패키징할 수 있습니다.
또한 게임 설치에 직접 설치할 수도 있습니다.
비하인드로, 언리얼 Pak과 일부 사용자 지정 코드를 사용하여 이를 달성했습니다.