= 새티스팩토리 모드 저장소에 모드 업로드 (ficsit.app)

멋진 모드를 만든 후에는 https://ficsit.app/[새티스팩토리 모드 저장소]가
다른 사람이 자신의 모드를 찾고 사용하기를 원하는 경우 업로드할 수 있는 가장 좋은 장소입니다.
SMR에 업로드된 모드는 자동으로 xref:index.adoc#_새티스팩토리_모드_관리자_일명_smm[모드 관리자]와 함께 작동합니다.
SMR에서 사용할 수 있는 모든 모드는 잠재적인 보안 문제가 있는지 확인되므로
SMR에서 모드를 사용하면 사용자가 모드가 안전하고 안전하다는 것을 신뢰할 수 있습니다.

모드를 업로드하는 과정은 매우 간단합니다.

== SMR 계정 생성

아직 계정을 만들지 않은 경우 https://ficsit.app/[SMR 홈페이지] 오른쪽 상단의 '로그인'을 클릭한 다음
기존 깃허브, 구글 또는 페이스북 계정으로 로그인하도록 선택하면 됩니다.

오른쪽 상단 모서리에 있는 사용자 아이콘에서 접근할 수 있는 설정 화면에서 프로필 사진과 표시 이름을 변경할 수 있습니다.

== 모드 페이지 생성

사용자가 다운로드할 모드 버전을 업로드하려면 먼저 모드 페이지를 만들어야 합니다.

시작하려면 SMR의 'Mods' 사이드바 탭에서 왼쪽 상단 모서리에 있는 `New Mod` 를 클릭하세요.

=== 모드에 대한 정보

다음으로 모드에 대한 정보를 추가해야 합니다.

* 'name'은 모드 목록과 브라우저에 표시될 제목입니다.
* 'short description'은 모드 아이콘 아래에 표시되는 요약 텍스트입니다.
* 'full description'은 마크다운 형식(https://ficsit.app/help[SMR 도움말 페이지]에서 자세히 알아보기)을 지원하며 사용자가 모든 모드 목록에서 모드를 보기 위해 클릭할 때 표시됩니다.
여기에 다음 정보를 포함하는 것이 좋습니다.
** 모드가 게임에 추가하는 내용 요약
** 실행 중인 모드의 스크린샷 또는 영상
** 모드를 시작하는 방법(허브 마일스톤을 통해 잠금 해제인지? 기본적으로 기능이 켜져 있는건지?)
** 나에게 연락할 수 있는 수단(스태프와 사용자가 모딩 디스코드에서 나를 식별할 수 있도록 나의 디스코드 사용자 태그가 바람직함)
** 깃허브 문제 페이지 또는 연락처 정보와 같은 버그 보고 수단
** 그 과정에서 도움을 준 사람들을 크레딧에 적기(예: 아이콘 제작, 코딩 도움)

아직 무엇을 작성해야 할지 확신이 서지 않아도 걱정하지 마세요. 나중에 돌아와서 이 필드를 편집할 수 있습니다.

=== 나의 모드 레퍼런스

이 화면에서 가장 중요한 필드 중 하나는 'Mod Reference' 필드입니다.
xref:Development/BeginnersGuide/index.adoc#_모드_레퍼런스[시작 안내서의 모드 레퍼런스 섹션]에 자세히 설명되어 있습니다. 모드 레퍼런스는 모드의 고유한 이름입니다.
참고로 모드의 플러그인 폴더와 C++ 소스 폴더({cpp}를 사용하는 경우)는 모드 레퍼런스와 이름이 같아야 합니다.
모드 레퍼런스에는 특수 문자나 공백이 포함될 수 없습니다.

[WARNING]
====
**SMR에 모드를 추가한 후에는 모드 레퍼런스를 변경할 수 없습니다!**

그러니 알맞게 적었는지 꼭 확인하세요! 최소 5번!
그리고 xref:Development/BeginnersGuide/index.adoc#_모드_레퍼런스[모드 레퍼런스 섹션]을 다시 읽어 모드의 다른 부분에서 이 동일한 값을 사용해야 하는지 이해했는지 확인하세요.
====

=== 아이콘 및 소스 링크

다음으로 모드의 표시 이미지로 사용할 이미지를 업로드해야 합니다.
또는 이 항목을 비워 둘 수 있으며 기본적으로 새티스팩토리 모딩 장비 로고가 됩니다.

깃허브와 같은 사이트에서 호스팅되는 경우 소스 코드에 대한 링크를 제공할 수도 있습니다.
소스 코드를 공개하면 다른 사람들이 귀하의 작업에서 배울 수 있고 다른 개발자가 모드 호환성을 디버깅하는 데 도움이 되므로 소스 코드를 공개하는 것이 좋습니다.

나중에 이 두 필드를 모두 편집할 수 있습니다.

=== 숨겨진 모드

생성 시 모드를 숨김으로 표시할 수도 있습니다.
나중에 돌아가서 편집할 수 있습니다.

모드가 숨겨진 경우 기본 모드 목록이나 SMM에서 탐색할 때, 사이트를 검색할 때 나타나지 않습니다.
그러나 다른 사용자는 여전히 프로필 페이지를 보고 찾을 수 있으며 사람들에게 직접 링크를 보낼 수 있습니다.

또한 모드를 숨기면 모딩 디스코드의 `#mod-updates` 채널에 메시지가 전송되지 않습니다.

=== 모드 페이지 제출

제출을 클릭하면 모드 페이지가 생성됩니다.

모드 페이지에는 URL의 일부로 모드의 모드 레퍼런스가 포함되어 있습니다.
예를 들어 `AreaActions` 레퍼런스를 사용하는 모드의 페이지는 `https://ficsit.app/mod/AreaActions` 가 됩니다.

플레이어가 모드를 사용할 수 있도록 하려면 꾸준히 버전을 업로드해야 합니다.
그때까지는 호환되는 버전이 없으므로 모드가 'Outdated'로 표시됩니다.
버전 제출 과정은 다음 섹션에서 다루겠습니다.

== 플러그인 내보내기

버전을 업로드하기 전에 모드의 uplugin 파일에서 편집해야 하는 몇 가지 필드가 있으며 그 후에 알파킷이 모드를 번들로 묶을 겁니다.

이것들은 xref:Development/BeginnersGuide/ReleaseMod.adoc[모드 페이지 출시하기]에서 자세히 다루고 있습니다.

== 버전 업로드

`.uplugin` 설정을 완료한 후에는 변경 사항을 포함하도록 알파킷으로 다시 패키징했는지 확인하세요.

모드의 모드 페이지로 이동한 다음 오른쪽 상단 모서리에서 'New Version'을 선택합니다.
이렇게 하면 버전 파일을 업로드하고 버전에 대한 추가 정보를 제공할 수 있는 페이지로 이동됩니다.

안정성 필드에 "Alpha", "Beta", "Release" 등을 입력하여 사용자가 이 버전의 모드가 얼마나 발전했다고 생각하는지 알게 해주세요.

`File` 필드 선택기에는 link:#_플러그인_내보내기[플러그인 내보내기 섹션]에서 추출한 압축 파일을 선택합니다.

마지막으로 `Changelog` 필드에는 이 버전에서의 변경점 등을 적어주세요.
또한 이 정보를 메인 모드 페이지에 있는 모드 설명의 'update history' 섹션에 복사하는 것이 좋습니다.

[TIP]
====
이전에 모드를 숨김으로 표시하기로 결정한 경우 첫 번째 버전을 업로드하기 전에 다시 표시해야 합니다!

그렇지 않으면 모드 출시에 대한 알림이 디스코드에 전송되지 않으며 아무도 사이트에서 모드를 (쉽게) 찾을 수 없습니다.
====

이제 모든 설정이 완료됐습니다. `Create` 를 누르면 업로드 과정이 시작되고 완료되면 모드를 사용할 수 있습니다.

[TIP]
====
업로드 전 https://ficsit.app/content-policy[콘텐츠 정책]을 꼭 읽어주세요!
====

업로드 중에 오류가 발생하면 이 화면에 오류가 표시됩니다.
xref:Development/BeginnersGuide/ReleaseMod.adoc#_smr_uplugin_유효성_검사기[uplugin 유효성 검사기]가 유용할 수 있습니다.
문제를 해결하는 방법을 잘 모르는 경우 디스코드에서 도움을 요청하는 것이 좋습니다.

== 승인 대기

블루프린트만 있는 모드를 업로드했다면 모든 설정이 완료되고 모드를 다운로드하여 사용할 준비가 된 것입니다!
그렇지만 아래 내용은 꼭 읽어 보시기 바랍니다.

C++ 모드를 업로드한 경우 자동 승인 과정에서 승인될 때까지 기다려야 사용자가 다운로드할 수 있습니다.
승인 과정은 일반적으로 약 1~3분 정도로 매우 빠르며 사용자가 SMR의 이용 약관을 위반하거나
플레이어의 컴퓨터에 해를 끼치는 콘텐츠를 업로드하지 않도록 하기 위해 존재합니다.

그 동안 모드 설명을 살펴보고 여기에 추가 정보를 추가하는 것이 좋습니다.
아래에서 자세히 알아보세요.

== 모드 페이지 다듬기

모드 설명은 모드를 사용할지 여부를 결정할 때 대부분의 플레이어가 보게 되는 내용이므로
체계적으로 유지하고 좋은 첫인상을 남기도록 노력하세요!
말하자면 모드 페이지를 보는 것이 '만족스러운' 경험이 되도록 노력해야 한다고 말할 수 있습니다.

사용자가 모드를 사용해 보도록 권장하려면 다음 단계를 수행하는 것이 좋습니다.

- 문법과 철자를 확인하세요! 다른 사람에게 당신의 설명을 교정하도록 요청하세요.
	하기 쉬운 일이고 올바른 문법을 가지고 있으면 더 전문적으로 보일 수 있습니다.

- 사진! 모드가 무엇을 할 수 있는지, 게임에서 건물이나 기능이 어떻게 보이는지 스크린샷을 찍으세요.
	다시 말하지만, 긴 설명은 https://ficsit.app/help[도움말 페이지]에서 도움을 받을 수 있는 마크다운 형식을 지원합니다.

- 도움, 문제 보고, 제안 남기기 등을 위해 연락할 수 있는 목록을 나열하세요.
	디스코드, 모드의 깃허브 페이지 또는 다른 곳을 통해 사용자가 모드와 관련된 문제를 어디에 보고하기를 원하시나요?
	사람들이 커뮤니티 디스코드에서 연락할 수 있도록 모드 설명에 디스코드 태그를 추가하고 모드 이름을 포함하도록 서버에서 닉네임을 변경하는 것을 고려하세요.

- 사용자에게 불분명할 수 있는 모드의 개념이나 기능을 설명하세요.
	모드 사용 방법에 대한 문서나 https://ficsit.app/guides[가이드]를 작성하지 않는 한 플레이어는 모드에서 모든 놀라운 새 콘텐츠를 사용하는 방법을 파악하는 데 어려움을 겪을 수 있습니다.

- 모드의 기능과 게임 내 사용을 위해 잠금 해제하는 방법을 나열하세요.
	콘텐츠가 잠금 해제되는 티어를 나열하는 것을 고려해보세요.

- 아이디어, 모델 등을 제공한 다른 사용자를 이름 또는 링크로 표시해 놓으세요.

== 모드의 향후 업데이트

나중에 모드의 새 버전을 업데이트할 때 `<모드 레퍼런스>.uplugin` 에서 변경해야 하는 유일한 항목은 `Version`, `VersionName` 및 `SemVersion` 필드일 가능성이 높습니다.
