= 모드 테스트

모드를 테스트하여 콘텐츠에 접근할 수 있고 버그가 없는지 확인하는 것은 개발의 중요한 단계입니다.
배포 전에 주의 깊게 테스트하면 버그를 수정하기 위해 여러 버전을 빠르게 연속해서 배포하지 않아도 됩니다.

이 페이지에는 모드 테스트와 관련된 몇 가지 유용한 리소스와 정보가 나열되어 있습니다.

== SML 로깅

SML 로깅은 특히 블루프린트 모드에 유용한 문제 해결 및 테스트 도구입니다.

xref:Development/ModLoader/Logging.adoc[로깅 페이지]에서 사용 및 구성 방법에 대한 자세한 정보를 찾을 수 있습니다.

로그 터미널 창에서 텍스트를 선택하면 '엔터'를 눌러 선택을 해제할 때까지 게임이 정지됩니다.
이것은 일반적으로 스크롤하기 전에 내용을 읽는 데 도움이 될 수 있습니다.

로그 터미널은 일반 윈도우 명령 프롬프트 창이므로 상단 표시줄을 마우스 오른쪽 버튼으로 클릭하고 터미널이 열릴 때마다 적용되는 창이 생성되는 위치 및 너비와 같은 몇 가지 기본 사용자 지정 값을 설정할 수 있습니다.
예를 들어 이를 사용하여 서브 모니터에서 항상 열 수 있습니다.
여기에서 설정한 값은 시스템의 모든 명령 프롬프트 인스턴스에 영향을 미칩니다.
창이 표시되는 위치를 제어하는 다른 방법은 아래의 link:#_시작_스크립트_개선_사항[시작 스크립트 개선 사항] 섹션을 참조하세요.

== 멀티플레이 테스트
=== 지침

몇 가지 간단한 단계로 멀티플레이 테스트를 위해 새티스팩토리 게임 2개를 실행하세요!

1. 아래 코드 블록의 내용으로 새 Powershell 스크립트를 생성하고 게임 설치 폴더의 첫 번째 줄을 편집합니다.
참고: 2, 3번째 줄은 플레이어 이름이며, 변경할 수 있습니다.

2. Powershell에서 스크립트를 실행하고(스크립트를 마우스 오른쪽 버튼으로 클릭하고 "PowerShell에서 실행"을 누름) 게임의 두 복사본이 로드될 때까지 기다립니다.

3. 게임 사본에서 저장 파일을 엽니다.

4. 일단 로드했으면 두 번째 게임 인스턴스로 이동하고 ` (백틱/그레이브) 키를 눌러 콘솔을 엽니다.
그런 다음 `open 127.0.0.1` 을 입력하고 Enter 키를 누릅니다.
이제 두 번째 인스턴스가 첫 번째 인스턴스에서 호스팅하는 게임에 연결됩니다.

[NOTE]
====
백틱을 사용하여 콘솔을 여는 것은 실제 키보드 레이아웃이 아닌 Windows 영국 키보드 레이아웃에서만 작동하는 것 같지만 Windows에서는 영국 키보드 레이아웃으로 설정합니다.
일부 다른 키보드 레이아웃에서는 F2가 대신 작동합니다.
콘솔을 여는 데 문제가 있는 경우 새티스팩토리의 `Input.ini` 파일(`%localappdata%\FactoryGame\Saved\Config\WindowsNoEditor\Input.ini` 에 있음)에서 설정을 편집하여 원하는 키로 콘솔 키를 변경할 수 있습니다.
====

=== Powershell로 스크립트 실행

[source,ps1]
----
$GameDir = "C:\Program Files\Epic Games\SatisfactoryEarlyAccess"
$Username1 = "Player1"
$Username2 = "Player2"

$Args1 = "-EpicPortal", "-NoSteamClient", "-NoMultiplayer", '-Username="'+$Username1+'"'
$Args2 = "-EpicPortal", "-NoSteamClient", "-NoMultiplayer", '-Username="'+$Username2+'"'

function BGProcess(){
    Start-Process -NoNewWindow @args
}

BGProcess "$($GameDir)\FactoryGame.exe" $Args1

sleep -m 5000

BGProcess "$($GameDir)\FactoryGame.exe" $Args2
----

=== 시작 스크립트 개선 사항

언리얼은 https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/CommandLineArguments/[많은] 기타 명령줄 인수를 지원하며, 그 중 일부는 멀티플레이 테스트에 유용할 수 있습니다.
예를 들어 `-WinX=0 -WinY=0` 은 화면 왼쪽 상단에서 게임을 엽니다.
콘솔 창(`ConsoleX` 및 `ConsoleY`)에 대해서도 유사한 인수가 있습니다.
`-WinX=1280 -WinY=720` 을 통해 게임을 실행할 해상도를 지정할 수도 있습니다.

다른 모니터에서 창을 열려면 인수에 대해 음수 또는 더 큰 숫자를 사용해야 합니다.
기본 모니터의 왼쪽 상단 모서리는 X=0, Y=0입니다.

이러한 옵션을 결합하면 아래에 표시된 것과 같은 시작 인수로 끝날 수 있습니다.
이렇게 하면 비정상적인 화면 비율을 희생하여 1920x1080 해상도 화면에서 각 인스턴스에 가능한 한
많은 화면 공간을 제공합니다 (제목 표시줄과 시작 메뉴 높이를 고려함).
[source,ps1]
----
$Args1 = "-EpicPortal", "-NoSteamClient", '-Username="'+$Username1+'"', "-WinX=0", "-WinY=32", "ResX=960", "ResY=1040"
$Args2 = "-EpicPortal", "-NoSteamClient", '-Username="'+$Username2+'"', "-WinX=960", "-WinY=32", "ResX=960", "ResY=1040"
----

== 실행 시 자동으로 맵 로드

모드를 테스트할 때 메인 메뉴와 달리 게임이 게임 세계에 자동으로 로드되도록 하여 로드 시간과 클릭 수를 줄일 수 있습니다.

이렇게 하려면 몇 가지 구성 설정으로 파일을 만들거나 기본 게임 구성에 추가해야 합니다.

시작하려면 다음을 포함하는 편리한 위치(예: 새티스팩토리 게임 설치 경로)에 `.ini` 파일을 생성합니다.

```
[/Script/EngineSettings.GameMapsSettings]
LocalMapOptions=??skipOnboarding?loadgame=LastLight_autosave_0
GameDefaultMap=/Game/FactoryGame/Map/GameLevel01/Persistent_Level.Persistent_Level
GameInstanceClass=/Script/FactoryGame.FGGameInstance
```

'LastLight_autosave_0' 자리에 원하는 세이브 파일의 이름을 넣으세요.
맵의 마지막 자동 세이브를 로드하는 것은 올바르게 형식을 지정한 경우에도 작동한다는 점에 유의하세요.
예제는 `LastLight` 라는 세이브의 최신 자동 세이브를 로드합니다.

이렇게 하면 해당 게임 세션의 주 메뉴로 돌아갈 수 없습니다. 그렇게 하려고 하면 선택한 게임 세이브를 다시 로드하게 됩니다.

사용할 수 있는 몇 가지 다른 플래그도 있습니다.

+++ <details><summary> +++
Archengius에서 FG 맵 옵션 전환:
+++ </summary><div> +++
....
Switches found in AFGGameMode::InitGame:

?skipOnboarding (skip landing animation)
?allowPossessAny (allow possessing any pawn on the map, even if player IDs don't match)
?loadgame=<SaveGame Name Here Without Path and extension>
?startloc<Start Location Tag Name> (see AFGGameMode::ChoosePlayerStart_Implementation)
?sessionName=<Session Name> (sets mSaveSessionName, so apparently it determines autosave file name and probably name visible to other players?)
?DayLength=<Day Length In Minutes>
?NightLength=<Night Length In Minutes>

General notes:
  Regarding Start Location Tag Name:
      - TRADING_POST is the hub APlayerStart actor tag
      - Any APlayerStart actor with matching PlayerStartTag is selected
  Regarding Session Name:
      - Apparently there is a system of "bundled saves" that I know nothing about. Further investigation is required.

Switches found in AFGGameSession:

?Visibility=SV_Private/SV_Public (Session visibility)
?adminpassword=<Admin Password used in console command AdminLogin to gain host privileges>

There is also ?bUseIpSockets linked with offline sessions
Apparently it disables EOS sockets and makes the game fall back to normal IPv4 sockets
....
+++ </div></details> +++

두 가지 방법 중 하나를 사용하여 게임을 시작할 수 있습니다.

=== 옵션 1 - 시작 스크립트를 사용한 사용자 지정 구성

`EngineINI` 명령 플래그에 지정된 구성 파일 경로를 사용하여 명령줄에서 게임을 시작할 수 있습니다.

예를 들어 파일 이름이 `LoadMapEngineConfiguration.ini` 인 경우 시작 명령은 다음과 같습니다.

```
"D:\SatisfactoryExperimental\FactoryGame\Binaries\Win64\FactoryGame-Win64-Shipping.exe" -EpicPortal -NoMultiplayer -Username=Player1 EngineINI="D:\SatisfactoryExperimental\LoadMapEngineConfiguration.ini"
```

게임이 설치된 위치를 가리키도록 이 예제 명령을 수정해야 합니다.

나중에 쉽게 실행할 수 있도록 배치 파일이나 powershell 스크립트에 저장할 수 있습니다.

=== 옵션 2 - 기본 게임 구성에 추가

구성을 위한 새 파일을 만드는 대신 `%localappdata%/FactoryGame/Saved/WindowsNoEditor/Engine.ini` 에 있는 기본 게임 구성을 편집할 수 있습니다.

이 옵션을 선택하면 모드가 설치되지 않은 경우에도 게임을 어디에서 실행하든 상관없이 이 구성을 사용하여 게임이 _항상_ 실행됩니다.
